### ISSUE TITLE
stream comparison fails for 2 identical files having same content

### ISSUE THREAD

**Issue by bhaskerchari** [fent/node-stream-equal#29] opened 2019-08-19 13:47 UTC
I am trying to use node-stream-equal to compare two zip files which actually may have a single excel/ppt/csv files and is zipped for compressing the size but the stream comparison always returns false.

```
var fs = require('fs');
var path = require('path');

function compareStreams(file1Path, file2Path) {
	const streamEqual = require('stream-equal');
	const fs = require('fs');
	var file1 = path.resolve(__dirname, file1Path);
	var file2 = path.resolve(__dirname, file2Path);

	let readStream1 = fs.createReadStream(file1);
	let readStream2 = fs.createReadStream(file2);
	streamEqual(readStream1, readStream2, (err, equal) => {
		console.log(equal); // true
	});
}
```

```
// This always logs false
compareStreams(''./excel1.zip'', './excel2.zip');
```

I have even tried unzipping it and directly comared the excel files still it logs false and I am sure the contents of excel files are exactly identical.
`compareStreams(''./excel1.xlsx'', './excel2.xlsx');`

But one thing I have noticed is if I create a copy of 1 file and compare with its copy then it is logging true.

`For ex: compareStreams(''./excel1.xlsx'', './excel1 - Copy.xlsx'); // logs true to console.`

I am wondering if it has something to do with the timestamp and especially the modified date of the file.

Any body has any suggestions on this?

**Comment by fent** [comment] 2019-08-19 14:11
if you are separately creating two excel files with the same content, excel may be saving some other metadata unique to that file, such as the timestamp. and so, the files will not be equal when compared byte by byte.

**Comment by bhaskerchari** [comment] 2019-08-20 04:33
Hi @fent,

I agree that could be the case and based on my requirement I want to compare 2 identical excel/ppt/csv files which may have exact same content. But I couldn't figure out how it can be done in an easier way either by stream comparison or even buffer comparison also didn't help.

I've done more research but not much success.

I'm just wondering how it would be possible to ignore certain things such as time stamp and any other metadata while doing comparison and only consider contents to match up.

But I didn't find any node package on the web which does what I am looking for...

**Comment by fent** [comment] 2019-08-20 05:54
try looking for an excel file reader/parser, then read the contents of the two files and compare those.

going to close this since it's not a bug

**Closed by fent** 2019-08-20 05:54 UTC
